include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/widget_test.dart"
    - "bin/cache/**"
    - test
    - assets/translations

linter:
  rules:
    # -  public_member_api_docs: false,
    alwasy_specify_types:
    sort_pub_dependencies:
    inference_failure_on_instance_creation:
